// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

package data;

public final class ImageMessage {
  private ImageMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ImageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required uint32 node_id = 2;
    /**
     * <code>required uint32 node_id = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required uint32 node_id = 2;</code>
     */
    int getNodeId();

    // required string user_id = 3;
    /**
     * <code>required string user_id = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string user_id = 3;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string user_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    // required string name = 10;
    /**
     * <code>required string name = 10;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 10;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 10;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string mime = 11;
    /**
     * <code>required string mime = 11;</code>
     */
    boolean hasMime();
    /**
     * <code>required string mime = 11;</code>
     */
    java.lang.String getMime();
    /**
     * <code>required string mime = 11;</code>
     */
    com.google.protobuf.ByteString
        getMimeBytes();

    // required uint64 length = 12;
    /**
     * <code>required uint64 length = 12;</code>
     */
    boolean hasLength();
    /**
     * <code>required uint64 length = 12;</code>
     */
    long getLength();

    // required uint64 created = 18;
    /**
     * <code>required uint64 created = 18;</code>
     */
    boolean hasCreated();
    /**
     * <code>required uint64 created = 18;</code>
     */
    long getCreated();

    // required uint64 modified = 19;
    /**
     * <code>required uint64 modified = 19;</code>
     */
    boolean hasModified();
    /**
     * <code>required uint64 modified = 19;</code>
     */
    long getModified();

    // optional string desc = 20;
    /**
     * <code>optional string desc = 20;</code>
     */
    boolean hasDesc();
    /**
     * <code>optional string desc = 20;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 20;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // optional .data.Image.Resolution size = 21;
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    boolean hasSize();
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    data.ImageMessage.Image.Resolution getSize();
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    data.ImageMessage.Image.ResolutionOrBuilder getSizeOrBuilder();

    // optional .data.Image.GeoPoint geo_location = 22;
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    boolean hasGeoLocation();
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    data.ImageMessage.Image.GeoPoint getGeoLocation();
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    data.ImageMessage.Image.GeoPointOrBuilder getGeoLocationOrBuilder();

    // optional uint64 timestamp = 23;
    /**
     * <code>optional uint64 timestamp = 23;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint64 timestamp = 23;</code>
     */
    long getTimestamp();

    // optional bytes data = 255;
    /**
     * <code>optional bytes data = 255;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 255;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code data.Image}
   */
  public static final class Image extends
      com.google.protobuf.GeneratedMessage
      implements ImageOrBuilder {
    // Use Image.newBuilder() to construct.
    private Image(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Image(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Image defaultInstance;
    public static Image getDefaultInstance() {
      return defaultInstance;
    }

    public Image getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Image(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nodeId_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              userId_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000010;
              mime_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000020;
              length_ = input.readUInt64();
              break;
            }
            case 144: {
              bitField0_ |= 0x00000040;
              created_ = input.readUInt64();
              break;
            }
            case 152: {
              bitField0_ |= 0x00000080;
              modified_ = input.readUInt64();
              break;
            }
            case 162: {
              bitField0_ |= 0x00000100;
              desc_ = input.readBytes();
              break;
            }
            case 170: {
              data.ImageMessage.Image.Resolution.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = size_.toBuilder();
              }
              size_ = input.readMessage(data.ImageMessage.Image.Resolution.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(size_);
                size_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 178: {
              data.ImageMessage.Image.GeoPoint.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = geoLocation_.toBuilder();
              }
              geoLocation_ = input.readMessage(data.ImageMessage.Image.GeoPoint.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(geoLocation_);
                geoLocation_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
            case 184: {
              bitField0_ |= 0x00000800;
              timestamp_ = input.readUInt64();
              break;
            }
            case 2042: {
              bitField0_ |= 0x00001000;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.ImageMessage.internal_static_data_Image_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.ImageMessage.internal_static_data_Image_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.ImageMessage.Image.class, data.ImageMessage.Image.Builder.class);
    }

    public static com.google.protobuf.Parser<Image> PARSER =
        new com.google.protobuf.AbstractParser<Image>() {
      public Image parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Image(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Image> getParserForType() {
      return PARSER;
    }

    public interface ResolutionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required uint32 width = 1;
      /**
       * <code>required uint32 width = 1;</code>
       */
      boolean hasWidth();
      /**
       * <code>required uint32 width = 1;</code>
       */
      int getWidth();

      // required uint32 height = 2;
      /**
       * <code>required uint32 height = 2;</code>
       */
      boolean hasHeight();
      /**
       * <code>required uint32 height = 2;</code>
       */
      int getHeight();
    }
    /**
     * Protobuf type {@code data.Image.Resolution}
     */
    public static final class Resolution extends
        com.google.protobuf.GeneratedMessage
        implements ResolutionOrBuilder {
      // Use Resolution.newBuilder() to construct.
      private Resolution(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Resolution(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Resolution defaultInstance;
      public static Resolution getDefaultInstance() {
        return defaultInstance;
      }

      public Resolution getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Resolution(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                width_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                height_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.ImageMessage.internal_static_data_Image_Resolution_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.ImageMessage.internal_static_data_Image_Resolution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.ImageMessage.Image.Resolution.class, data.ImageMessage.Image.Resolution.Builder.class);
      }

      public static com.google.protobuf.Parser<Resolution> PARSER =
          new com.google.protobuf.AbstractParser<Resolution>() {
        public Resolution parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Resolution(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Resolution> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required uint32 width = 1;
      public static final int WIDTH_FIELD_NUMBER = 1;
      private int width_;
      /**
       * <code>required uint32 width = 1;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 width = 1;</code>
       */
      public int getWidth() {
        return width_;
      }

      // required uint32 height = 2;
      public static final int HEIGHT_FIELD_NUMBER = 2;
      private int height_;
      /**
       * <code>required uint32 height = 2;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 height = 2;</code>
       */
      public int getHeight() {
        return height_;
      }

      private void initFields() {
        width_ = 0;
        height_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasWidth()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, width_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, height_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, width_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, height_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static data.ImageMessage.Image.Resolution parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static data.ImageMessage.Image.Resolution parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static data.ImageMessage.Image.Resolution parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static data.ImageMessage.Image.Resolution parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(data.ImageMessage.Image.Resolution prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code data.Image.Resolution}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements data.ImageMessage.Image.ResolutionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return data.ImageMessage.internal_static_data_Image_Resolution_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return data.ImageMessage.internal_static_data_Image_Resolution_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  data.ImageMessage.Image.Resolution.class, data.ImageMessage.Image.Resolution.Builder.class);
        }

        // Construct using data.ImageMessage.Image.Resolution.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          width_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          height_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return data.ImageMessage.internal_static_data_Image_Resolution_descriptor;
        }

        public data.ImageMessage.Image.Resolution getDefaultInstanceForType() {
          return data.ImageMessage.Image.Resolution.getDefaultInstance();
        }

        public data.ImageMessage.Image.Resolution build() {
          data.ImageMessage.Image.Resolution result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public data.ImageMessage.Image.Resolution buildPartial() {
          data.ImageMessage.Image.Resolution result = new data.ImageMessage.Image.Resolution(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.width_ = width_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.height_ = height_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof data.ImageMessage.Image.Resolution) {
            return mergeFrom((data.ImageMessage.Image.Resolution)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(data.ImageMessage.Image.Resolution other) {
          if (other == data.ImageMessage.Image.Resolution.getDefaultInstance()) return this;
          if (other.hasWidth()) {
            setWidth(other.getWidth());
          }
          if (other.hasHeight()) {
            setHeight(other.getHeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasWidth()) {
            
            return false;
          }
          if (!hasHeight()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          data.ImageMessage.Image.Resolution parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (data.ImageMessage.Image.Resolution) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required uint32 width = 1;
        private int width_ ;
        /**
         * <code>required uint32 width = 1;</code>
         */
        public boolean hasWidth() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint32 width = 1;</code>
         */
        public int getWidth() {
          return width_;
        }
        /**
         * <code>required uint32 width = 1;</code>
         */
        public Builder setWidth(int value) {
          bitField0_ |= 0x00000001;
          width_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 width = 1;</code>
         */
        public Builder clearWidth() {
          bitField0_ = (bitField0_ & ~0x00000001);
          width_ = 0;
          onChanged();
          return this;
        }

        // required uint32 height = 2;
        private int height_ ;
        /**
         * <code>required uint32 height = 2;</code>
         */
        public boolean hasHeight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint32 height = 2;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>required uint32 height = 2;</code>
         */
        public Builder setHeight(int value) {
          bitField0_ |= 0x00000002;
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint32 height = 2;</code>
         */
        public Builder clearHeight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          height_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:data.Image.Resolution)
      }

      static {
        defaultInstance = new Resolution(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:data.Image.Resolution)
    }

    public interface GeoPointOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required double lat = 1;
      /**
       * <code>required double lat = 1;</code>
       */
      boolean hasLat();
      /**
       * <code>required double lat = 1;</code>
       */
      double getLat();

      // required double lng = 2;
      /**
       * <code>required double lng = 2;</code>
       */
      boolean hasLng();
      /**
       * <code>required double lng = 2;</code>
       */
      double getLng();
    }
    /**
     * Protobuf type {@code data.Image.GeoPoint}
     */
    public static final class GeoPoint extends
        com.google.protobuf.GeneratedMessage
        implements GeoPointOrBuilder {
      // Use GeoPoint.newBuilder() to construct.
      private GeoPoint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private GeoPoint(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final GeoPoint defaultInstance;
      public static GeoPoint getDefaultInstance() {
        return defaultInstance;
      }

      public GeoPoint getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private GeoPoint(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                lat_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                lng_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.ImageMessage.internal_static_data_Image_GeoPoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.ImageMessage.internal_static_data_Image_GeoPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.ImageMessage.Image.GeoPoint.class, data.ImageMessage.Image.GeoPoint.Builder.class);
      }

      public static com.google.protobuf.Parser<GeoPoint> PARSER =
          new com.google.protobuf.AbstractParser<GeoPoint>() {
        public GeoPoint parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GeoPoint(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<GeoPoint> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required double lat = 1;
      public static final int LAT_FIELD_NUMBER = 1;
      private double lat_;
      /**
       * <code>required double lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double lat = 1;</code>
       */
      public double getLat() {
        return lat_;
      }

      // required double lng = 2;
      public static final int LNG_FIELD_NUMBER = 2;
      private double lng_;
      /**
       * <code>required double lng = 2;</code>
       */
      public boolean hasLng() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double lng = 2;</code>
       */
      public double getLng() {
        return lng_;
      }

      private void initFields() {
        lat_ = 0D;
        lng_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasLat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLng()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, lng_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, lng_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static data.ImageMessage.Image.GeoPoint parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static data.ImageMessage.Image.GeoPoint parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static data.ImageMessage.Image.GeoPoint parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static data.ImageMessage.Image.GeoPoint parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(data.ImageMessage.Image.GeoPoint prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code data.Image.GeoPoint}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements data.ImageMessage.Image.GeoPointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return data.ImageMessage.internal_static_data_Image_GeoPoint_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return data.ImageMessage.internal_static_data_Image_GeoPoint_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  data.ImageMessage.Image.GeoPoint.class, data.ImageMessage.Image.GeoPoint.Builder.class);
        }

        // Construct using data.ImageMessage.Image.GeoPoint.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          lat_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          lng_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return data.ImageMessage.internal_static_data_Image_GeoPoint_descriptor;
        }

        public data.ImageMessage.Image.GeoPoint getDefaultInstanceForType() {
          return data.ImageMessage.Image.GeoPoint.getDefaultInstance();
        }

        public data.ImageMessage.Image.GeoPoint build() {
          data.ImageMessage.Image.GeoPoint result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public data.ImageMessage.Image.GeoPoint buildPartial() {
          data.ImageMessage.Image.GeoPoint result = new data.ImageMessage.Image.GeoPoint(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lat_ = lat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lng_ = lng_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof data.ImageMessage.Image.GeoPoint) {
            return mergeFrom((data.ImageMessage.Image.GeoPoint)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(data.ImageMessage.Image.GeoPoint other) {
          if (other == data.ImageMessage.Image.GeoPoint.getDefaultInstance()) return this;
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLng()) {
            setLng(other.getLng());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLat()) {
            
            return false;
          }
          if (!hasLng()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          data.ImageMessage.Image.GeoPoint parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (data.ImageMessage.Image.GeoPoint) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required double lat = 1;
        private double lat_ ;
        /**
         * <code>required double lat = 1;</code>
         */
        public boolean hasLat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required double lat = 1;</code>
         */
        public double getLat() {
          return lat_;
        }
        /**
         * <code>required double lat = 1;</code>
         */
        public Builder setLat(double value) {
          bitField0_ |= 0x00000001;
          lat_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double lat = 1;</code>
         */
        public Builder clearLat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lat_ = 0D;
          onChanged();
          return this;
        }

        // required double lng = 2;
        private double lng_ ;
        /**
         * <code>required double lng = 2;</code>
         */
        public boolean hasLng() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double lng = 2;</code>
         */
        public double getLng() {
          return lng_;
        }
        /**
         * <code>required double lng = 2;</code>
         */
        public Builder setLng(double value) {
          bitField0_ |= 0x00000002;
          lng_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double lng = 2;</code>
         */
        public Builder clearLng() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lng_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:data.Image.GeoPoint)
      }

      static {
        defaultInstance = new GeoPoint(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:data.Image.GeoPoint)
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 node_id = 2;
    public static final int NODE_ID_FIELD_NUMBER = 2;
    private int nodeId_;
    /**
     * <code>required uint32 node_id = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 node_id = 2;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    // required string user_id = 3;
    public static final int USER_ID_FIELD_NUMBER = 3;
    private java.lang.Object userId_;
    /**
     * <code>required string user_id = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string user_id = 3;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 10;
    public static final int NAME_FIELD_NUMBER = 10;
    private java.lang.Object name_;
    /**
     * <code>required string name = 10;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string name = 10;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string mime = 11;
    public static final int MIME_FIELD_NUMBER = 11;
    private java.lang.Object mime_;
    /**
     * <code>required string mime = 11;</code>
     */
    public boolean hasMime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string mime = 11;</code>
     */
    public java.lang.String getMime() {
      java.lang.Object ref = mime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getMimeBytes() {
      java.lang.Object ref = mime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint64 length = 12;
    public static final int LENGTH_FIELD_NUMBER = 12;
    private long length_;
    /**
     * <code>required uint64 length = 12;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint64 length = 12;</code>
     */
    public long getLength() {
      return length_;
    }

    // required uint64 created = 18;
    public static final int CREATED_FIELD_NUMBER = 18;
    private long created_;
    /**
     * <code>required uint64 created = 18;</code>
     */
    public boolean hasCreated() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required uint64 created = 18;</code>
     */
    public long getCreated() {
      return created_;
    }

    // required uint64 modified = 19;
    public static final int MODIFIED_FIELD_NUMBER = 19;
    private long modified_;
    /**
     * <code>required uint64 modified = 19;</code>
     */
    public boolean hasModified() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required uint64 modified = 19;</code>
     */
    public long getModified() {
      return modified_;
    }

    // optional string desc = 20;
    public static final int DESC_FIELD_NUMBER = 20;
    private java.lang.Object desc_;
    /**
     * <code>optional string desc = 20;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string desc = 20;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string desc = 20;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .data.Image.Resolution size = 21;
    public static final int SIZE_FIELD_NUMBER = 21;
    private data.ImageMessage.Image.Resolution size_;
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    public data.ImageMessage.Image.Resolution getSize() {
      return size_;
    }
    /**
     * <code>optional .data.Image.Resolution size = 21;</code>
     */
    public data.ImageMessage.Image.ResolutionOrBuilder getSizeOrBuilder() {
      return size_;
    }

    // optional .data.Image.GeoPoint geo_location = 22;
    public static final int GEO_LOCATION_FIELD_NUMBER = 22;
    private data.ImageMessage.Image.GeoPoint geoLocation_;
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    public boolean hasGeoLocation() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    public data.ImageMessage.Image.GeoPoint getGeoLocation() {
      return geoLocation_;
    }
    /**
     * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
     */
    public data.ImageMessage.Image.GeoPointOrBuilder getGeoLocationOrBuilder() {
      return geoLocation_;
    }

    // optional uint64 timestamp = 23;
    public static final int TIMESTAMP_FIELD_NUMBER = 23;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 23;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 timestamp = 23;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional bytes data = 255;
    public static final int DATA_FIELD_NUMBER = 255;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 255;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bytes data = 255;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      id_ = "";
      nodeId_ = 0;
      userId_ = "";
      name_ = "";
      mime_ = "";
      length_ = 0L;
      created_ = 0L;
      modified_ = 0L;
      desc_ = "";
      size_ = data.ImageMessage.Image.Resolution.getDefaultInstance();
      geoLocation_ = data.ImageMessage.Image.GeoPoint.getDefaultInstance();
      timestamp_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModified()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasSize()) {
        if (!getSize().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGeoLocation()) {
        if (!getGeoLocation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(10, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(11, getMimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(12, length_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(18, created_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(19, modified_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(20, getDescBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(21, size_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(22, geoLocation_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(23, timestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(255, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getMimeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, length_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(18, created_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(19, modified_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, getDescBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(21, size_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(22, geoLocation_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(23, timestamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(255, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static data.ImageMessage.Image parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ImageMessage.Image parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ImageMessage.Image parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.ImageMessage.Image parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.ImageMessage.Image parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.ImageMessage.Image parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static data.ImageMessage.Image parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static data.ImageMessage.Image parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static data.ImageMessage.Image parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.ImageMessage.Image parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(data.ImageMessage.Image prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.Image}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements data.ImageMessage.ImageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.ImageMessage.internal_static_data_Image_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.ImageMessage.internal_static_data_Image_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.ImageMessage.Image.class, data.ImageMessage.Image.Builder.class);
      }

      // Construct using data.ImageMessage.Image.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSizeFieldBuilder();
          getGeoLocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        mime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        created_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        modified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        if (sizeBuilder_ == null) {
          size_ = data.ImageMessage.Image.Resolution.getDefaultInstance();
        } else {
          sizeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        if (geoLocationBuilder_ == null) {
          geoLocation_ = data.ImageMessage.Image.GeoPoint.getDefaultInstance();
        } else {
          geoLocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.ImageMessage.internal_static_data_Image_descriptor;
      }

      public data.ImageMessage.Image getDefaultInstanceForType() {
        return data.ImageMessage.Image.getDefaultInstance();
      }

      public data.ImageMessage.Image build() {
        data.ImageMessage.Image result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public data.ImageMessage.Image buildPartial() {
        data.ImageMessage.Image result = new data.ImageMessage.Image(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mime_ = mime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.created_ = created_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.modified_ = modified_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (sizeBuilder_ == null) {
          result.size_ = size_;
        } else {
          result.size_ = sizeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (geoLocationBuilder_ == null) {
          result.geoLocation_ = geoLocation_;
        } else {
          result.geoLocation_ = geoLocationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.ImageMessage.Image) {
          return mergeFrom((data.ImageMessage.Image)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.ImageMessage.Image other) {
        if (other == data.ImageMessage.Image.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000004;
          userId_ = other.userId_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasMime()) {
          bitField0_ |= 0x00000010;
          mime_ = other.mime_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasCreated()) {
          setCreated(other.getCreated());
        }
        if (other.hasModified()) {
          setModified(other.getModified());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000100;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasSize()) {
          mergeSize(other.getSize());
        }
        if (other.hasGeoLocation()) {
          mergeGeoLocation(other.getGeoLocation());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasNodeId()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasMime()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        if (!hasCreated()) {
          
          return false;
        }
        if (!hasModified()) {
          
          return false;
        }
        if (hasSize()) {
          if (!getSize().isInitialized()) {
            
            return false;
          }
        }
        if (hasGeoLocation()) {
          if (!getGeoLocation().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.ImageMessage.Image parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.ImageMessage.Image) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required uint32 node_id = 2;
      private int nodeId_ ;
      /**
       * <code>required uint32 node_id = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 node_id = 2;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required uint32 node_id = 2;</code>
       */
      public Builder setNodeId(int value) {
        bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 node_id = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      // required string user_id = 3;
      private java.lang.Object userId_ = "";
      /**
       * <code>required string user_id = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string user_id = 3;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_id = 3;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_id = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }

      // required string name = 10;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 10;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string name = 10;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 10;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      // required string mime = 11;
      private java.lang.Object mime_ = "";
      /**
       * <code>required string mime = 11;</code>
       */
      public boolean hasMime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string mime = 11;</code>
       */
      public java.lang.String getMime() {
        java.lang.Object ref = mime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mime = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMimeBytes() {
        java.lang.Object ref = mime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mime = 11;</code>
       */
      public Builder setMime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mime = 11;</code>
       */
      public Builder clearMime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mime_ = getDefaultInstance().getMime();
        onChanged();
        return this;
      }
      /**
       * <code>required string mime = 11;</code>
       */
      public Builder setMimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mime_ = value;
        onChanged();
        return this;
      }

      // required uint64 length = 12;
      private long length_ ;
      /**
       * <code>required uint64 length = 12;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint64 length = 12;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>required uint64 length = 12;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000020;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 length = 12;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        length_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 created = 18;
      private long created_ ;
      /**
       * <code>required uint64 created = 18;</code>
       */
      public boolean hasCreated() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required uint64 created = 18;</code>
       */
      public long getCreated() {
        return created_;
      }
      /**
       * <code>required uint64 created = 18;</code>
       */
      public Builder setCreated(long value) {
        bitField0_ |= 0x00000040;
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 created = 18;</code>
       */
      public Builder clearCreated() {
        bitField0_ = (bitField0_ & ~0x00000040);
        created_ = 0L;
        onChanged();
        return this;
      }

      // required uint64 modified = 19;
      private long modified_ ;
      /**
       * <code>required uint64 modified = 19;</code>
       */
      public boolean hasModified() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required uint64 modified = 19;</code>
       */
      public long getModified() {
        return modified_;
      }
      /**
       * <code>required uint64 modified = 19;</code>
       */
      public Builder setModified(long value) {
        bitField0_ |= 0x00000080;
        modified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 modified = 19;</code>
       */
      public Builder clearModified() {
        bitField0_ = (bitField0_ & ~0x00000080);
        modified_ = 0L;
        onChanged();
        return this;
      }

      // optional string desc = 20;
      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 20;</code>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string desc = 20;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 20;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 20;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 20;</code>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000100);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 20;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        desc_ = value;
        onChanged();
        return this;
      }

      // optional .data.Image.Resolution size = 21;
      private data.ImageMessage.Image.Resolution size_ = data.ImageMessage.Image.Resolution.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          data.ImageMessage.Image.Resolution, data.ImageMessage.Image.Resolution.Builder, data.ImageMessage.Image.ResolutionOrBuilder> sizeBuilder_;
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public data.ImageMessage.Image.Resolution getSize() {
        if (sizeBuilder_ == null) {
          return size_;
        } else {
          return sizeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public Builder setSize(data.ImageMessage.Image.Resolution value) {
        if (sizeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          size_ = value;
          onChanged();
        } else {
          sizeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public Builder setSize(
          data.ImageMessage.Image.Resolution.Builder builderForValue) {
        if (sizeBuilder_ == null) {
          size_ = builderForValue.build();
          onChanged();
        } else {
          sizeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public Builder mergeSize(data.ImageMessage.Image.Resolution value) {
        if (sizeBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              size_ != data.ImageMessage.Image.Resolution.getDefaultInstance()) {
            size_ =
              data.ImageMessage.Image.Resolution.newBuilder(size_).mergeFrom(value).buildPartial();
          } else {
            size_ = value;
          }
          onChanged();
        } else {
          sizeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public Builder clearSize() {
        if (sizeBuilder_ == null) {
          size_ = data.ImageMessage.Image.Resolution.getDefaultInstance();
          onChanged();
        } else {
          sizeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public data.ImageMessage.Image.Resolution.Builder getSizeBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getSizeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      public data.ImageMessage.Image.ResolutionOrBuilder getSizeOrBuilder() {
        if (sizeBuilder_ != null) {
          return sizeBuilder_.getMessageOrBuilder();
        } else {
          return size_;
        }
      }
      /**
       * <code>optional .data.Image.Resolution size = 21;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          data.ImageMessage.Image.Resolution, data.ImageMessage.Image.Resolution.Builder, data.ImageMessage.Image.ResolutionOrBuilder> 
          getSizeFieldBuilder() {
        if (sizeBuilder_ == null) {
          sizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              data.ImageMessage.Image.Resolution, data.ImageMessage.Image.Resolution.Builder, data.ImageMessage.Image.ResolutionOrBuilder>(
                  size_,
                  getParentForChildren(),
                  isClean());
          size_ = null;
        }
        return sizeBuilder_;
      }

      // optional .data.Image.GeoPoint geo_location = 22;
      private data.ImageMessage.Image.GeoPoint geoLocation_ = data.ImageMessage.Image.GeoPoint.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          data.ImageMessage.Image.GeoPoint, data.ImageMessage.Image.GeoPoint.Builder, data.ImageMessage.Image.GeoPointOrBuilder> geoLocationBuilder_;
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public boolean hasGeoLocation() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public data.ImageMessage.Image.GeoPoint getGeoLocation() {
        if (geoLocationBuilder_ == null) {
          return geoLocation_;
        } else {
          return geoLocationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public Builder setGeoLocation(data.ImageMessage.Image.GeoPoint value) {
        if (geoLocationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          geoLocation_ = value;
          onChanged();
        } else {
          geoLocationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public Builder setGeoLocation(
          data.ImageMessage.Image.GeoPoint.Builder builderForValue) {
        if (geoLocationBuilder_ == null) {
          geoLocation_ = builderForValue.build();
          onChanged();
        } else {
          geoLocationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public Builder mergeGeoLocation(data.ImageMessage.Image.GeoPoint value) {
        if (geoLocationBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              geoLocation_ != data.ImageMessage.Image.GeoPoint.getDefaultInstance()) {
            geoLocation_ =
              data.ImageMessage.Image.GeoPoint.newBuilder(geoLocation_).mergeFrom(value).buildPartial();
          } else {
            geoLocation_ = value;
          }
          onChanged();
        } else {
          geoLocationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public Builder clearGeoLocation() {
        if (geoLocationBuilder_ == null) {
          geoLocation_ = data.ImageMessage.Image.GeoPoint.getDefaultInstance();
          onChanged();
        } else {
          geoLocationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public data.ImageMessage.Image.GeoPoint.Builder getGeoLocationBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getGeoLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      public data.ImageMessage.Image.GeoPointOrBuilder getGeoLocationOrBuilder() {
        if (geoLocationBuilder_ != null) {
          return geoLocationBuilder_.getMessageOrBuilder();
        } else {
          return geoLocation_;
        }
      }
      /**
       * <code>optional .data.Image.GeoPoint geo_location = 22;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          data.ImageMessage.Image.GeoPoint, data.ImageMessage.Image.GeoPoint.Builder, data.ImageMessage.Image.GeoPointOrBuilder> 
          getGeoLocationFieldBuilder() {
        if (geoLocationBuilder_ == null) {
          geoLocationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              data.ImageMessage.Image.GeoPoint, data.ImageMessage.Image.GeoPoint.Builder, data.ImageMessage.Image.GeoPointOrBuilder>(
                  geoLocation_,
                  getParentForChildren(),
                  isClean());
          geoLocation_ = null;
        }
        return geoLocationBuilder_;
      }

      // optional uint64 timestamp = 23;
      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 23;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 timestamp = 23;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 23;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000800;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 23;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000800);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes data = 255;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 255;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bytes data = 255;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 255;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 255;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00001000);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:data.Image)
    }

    static {
      defaultInstance = new Image(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:data.Image)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Image_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_Image_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Image_Resolution_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_Image_Resolution_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Image_GeoPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_Image_GeoPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013image.proto\022\004data\"\331\002\n\005Image\022\n\n\002id\030\001 \002(" +
      "\t\022\017\n\007node_id\030\002 \002(\r\022\017\n\007user_id\030\003 \002(\t\022\014\n\004n" +
      "ame\030\n \002(\t\022\014\n\004mime\030\013 \002(\t\022\016\n\006length\030\014 \002(\004\022" +
      "\017\n\007created\030\022 \002(\004\022\020\n\010modified\030\023 \002(\004\022\014\n\004de" +
      "sc\030\024 \001(\t\022$\n\004size\030\025 \001(\0132\026.data.Image.Reso" +
      "lution\022*\n\014geo_location\030\026 \001(\0132\024.data.Imag" +
      "e.GeoPoint\022\021\n\ttimestamp\030\027 \001(\004\022\r\n\004data\030\377\001" +
      " \001(\014\032+\n\nResolution\022\r\n\005width\030\001 \002(\r\022\016\n\006hei" +
      "ght\030\002 \002(\r\032$\n\010GeoPoint\022\013\n\003lat\030\001 \002(\001\022\013\n\003ln" +
      "g\030\002 \002(\001B\026\n\004dataB\014ImageMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_data_Image_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_data_Image_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_Image_descriptor,
              new java.lang.String[] { "Id", "NodeId", "UserId", "Name", "Mime", "Length", "Created", "Modified", "Desc", "Size", "GeoLocation", "Timestamp", "Data", });
          internal_static_data_Image_Resolution_descriptor =
            internal_static_data_Image_descriptor.getNestedTypes().get(0);
          internal_static_data_Image_Resolution_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_Image_Resolution_descriptor,
              new java.lang.String[] { "Width", "Height", });
          internal_static_data_Image_GeoPoint_descriptor =
            internal_static_data_Image_descriptor.getNestedTypes().get(1);
          internal_static_data_Image_GeoPoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_Image_GeoPoint_descriptor,
              new java.lang.String[] { "Lat", "Lng", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
