# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='image',
  serialized_pb='\n\x0bimage.proto\x12\x05image\"\xae\x03\n\x05Image\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07node_id\x18\x02 \x02(\r\x12\x0f\n\x07user_id\x18\x03 \x02(\t\x12\x0c\n\x04name\x18\n \x02(\t\x12\x0c\n\x04mime\x18\x0b \x02(\t\x12\x0c\n\x04\x64\x65sc\x18\x0c \x02(\t\x12\x0e\n\x06length\x18\r \x02(\x04\x12\x10\n\x08\x64\x61tetime\x18\x0e \x02(\x04\x12%\n\x04size\x18\x0f \x02(\x0b\x32\x17.image.Image.Resolution\x12.\n\roriginal_size\x18\x14 \x01(\x0b\x32\x17.image.Image.Resolution\x12.\n\x0cgeo_location\x18\x15 \x01(\x0b\x32\x18.image.Image.GeoLocation\x12\x19\n\x11original_datetime\x18\x16 \x01(\x04\x12\x17\n\x0fupload_datetime\x18\x17 \x01(\x04\x12\r\n\x04\x64\x61ta\x18\xff\x01 \x01(\x0c\x1a+\n\nResolution\x12\r\n\x05width\x18\x01 \x02(\r\x12\x0e\n\x06height\x18\x02 \x02(\r\x1a\x34\n\x0bGeoLocation\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lng\x18\x02 \x02(\x01\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x01\x42\x17\n\x05imageB\x0cImageMessageH\x01')




_IMAGE_RESOLUTION = _descriptor.Descriptor(
  name='Resolution',
  full_name='image.Image.Resolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='image.Image.Resolution.width', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='image.Image.Resolution.height', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=356,
  serialized_end=399,
)

_IMAGE_GEOLOCATION = _descriptor.Descriptor(
  name='GeoLocation',
  full_name='image.Image.GeoLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='image.Image.GeoLocation.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lng', full_name='image.Image.GeoLocation.lng', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alt', full_name='image.Image.GeoLocation.alt', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=401,
  serialized_end=453,
)

_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='image.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='image.Image.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='image.Image.node_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='image.Image.user_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='image.Image.name', index=3,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mime', full_name='image.Image.mime', index=4,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desc', full_name='image.Image.desc', index=5,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='image.Image.length', index=6,
      number=13, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='image.Image.datetime', index=7,
      number=14, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='image.Image.size', index=8,
      number=15, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='original_size', full_name='image.Image.original_size', index=9,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geo_location', full_name='image.Image.geo_location', index=10,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='original_datetime', full_name='image.Image.original_datetime', index=11,
      number=22, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upload_datetime', full_name='image.Image.upload_datetime', index=12,
      number=23, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='image.Image.data', index=13,
      number=255, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGE_RESOLUTION, _IMAGE_GEOLOCATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=453,
)

_IMAGE_RESOLUTION.containing_type = _IMAGE;
_IMAGE_GEOLOCATION.containing_type = _IMAGE;
_IMAGE.fields_by_name['size'].message_type = _IMAGE_RESOLUTION
_IMAGE.fields_by_name['original_size'].message_type = _IMAGE_RESOLUTION
_IMAGE.fields_by_name['geo_location'].message_type = _IMAGE_GEOLOCATION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE

class Image(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Resolution(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _IMAGE_RESOLUTION

    # @@protoc_insertion_point(class_scope:image.Image.Resolution)

  class GeoLocation(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _IMAGE_GEOLOCATION

    # @@protoc_insertion_point(class_scope:image.Image.GeoLocation)
  DESCRIPTOR = _IMAGE

  # @@protoc_insertion_point(class_scope:image.Image)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\005imageB\014ImageMessageH\001')
# @@protoc_insertion_point(module_scope)
