# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meta.proto',
  package='meta',
  serialized_pb='\n\nmeta.proto\x12\x04meta\"\x8b\x01\n\x05Image\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x11\n\tprocessed\x18\x03 \x01(\x08\x12&\n\x08metadata\x18\x04 \x03(\x0b\x32\x14.meta.Image.Metadata\x1a\'\n\x08Metadata\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\tB\x08\n\x04metaH\x01')




_IMAGE_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='meta.Image.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='meta.Image.Metadata.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='meta.Image.Metadata.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=160,
)

_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='meta.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='meta.Image.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='meta.Image.filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='processed', full_name='meta.Image.processed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='meta.Image.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGE_METADATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=160,
)

_IMAGE_METADATA.containing_type = _IMAGE;
_IMAGE.fields_by_name['metadata'].message_type = _IMAGE_METADATA
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE

class Image(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Metadata(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _IMAGE_METADATA

    # @@protoc_insertion_point(class_scope:meta.Image.Metadata)
  DESCRIPTOR = _IMAGE

  # @@protoc_insertion_point(class_scope:meta.Image)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\004metaH\001')
# @@protoc_insertion_point(module_scope)
